# Generated by Django 5.1.2 on 2024-11-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courseregister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
    ]
