# Generated by Django 5.1.2 on 2024-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_userprofile_delete_courseregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=None)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
